name: Detect Code Deletions

on:  
  pull_request:
    branches:
      - main
jobs:
  delete-detection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Git Difference
        run: git diff --name-only
      
      - name: Print GitHub Context
        run: |
          echo "Base Ref: ${{github.base_ref}}"
          echo "Head Ref: ${{github.head_ref}}"



