name: Detect Code Risk

on:
  workflow_call:

jobs:
  detect-risk:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v4
        with:
          repository: praveen-devops-labs/jenkins-demo-app-1
          ref: main
          fetch-depth: 0

      - name: Verify Script Exists
        run: ls -R .github

      - name: Make Script Executable
        run: chmod +x .github/scripts/detect_risk.sh

      - name: Run Risk Detection
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: .github/scripts/detect_risk.sh
