name: Detect Code Risk

on:  
  pull_request:
    branches:
      - dev-login
      - qa-testing
jobs:
  detect-deletions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Run deletion detector
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GCHAT_WEBHOOK: ${{ secrets.GCHAT_WEBHOOK }}
        run: |
          chmod +x .github/scripts/detect_deletions.sh
          .github/scripts/detect_deletions.sh
