name: Trigger Jenkins Orchestration Pipeline

on:
  workflow_call:
    
jobs:
    trigger-orchestrator-pipeline:
        if: github.event.pull_request.merged == true    
        runs-on: ubuntu-latest
        steps:
            - name: Trigger Jenkins Orchestration Pipeline
              env:
                  JENKINS_URL: ${{ secrets.JENKINS_URL }}
                  JENKINS_USER: ${{ secrets.JENKINS_USER }}
                  JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
              run: |
                  curl -X POST \
                    "${JENKINS_URL}/works/Orchestrator-Pipeline/" \
                    --user "${JENKINS_USER}:${JENKINS_TOKEN}" \
                    --data-urlencode "REPO_NAME=${{ github.event.repository.name }}" \
                    --data-urlencode "BRANCH_NAME=${{ github.event.pull_request.base.ref }}" \
                    --data-urlencode "COMMIT_SHA=${{ github.sha }}"