name: Trigger Jenkins Orchestration Pipeline

on:
  pull_request:
    branches:
      - dev-login
      - qa-testing
    types:
      - closed

jobs:
  trigger-orchestrator:
    if: github.event.pull_request.merged == true

    uses: <ORG>/<REPO>/.github/workflows/trigger-orchestrator-reusable.yml@main

    secrets: inherit
